Package {
  name: msgs
  description: "Interface Messages"
  author: "Konstantinos Xanthopoulos"
}

Object Header {
  timestamp: int
  id: int
}

Object thermoProperties {
  temperature: float
  humidity: float
}

PubSubMessage ThermoSensorMsg {
  temperature: float
}

PubSubMessage ThermoSensorMsg2 {
  temperature: float
  humidity: float '10'
}

PubSubMessage SonarSensorMsg {
  range: float
  hfov: float
  vfov: float
}

