
Package {
  name: msgs
  description: "Demo messages"
  author: "Konstantinos Xanthopoulos"
}

Object EmptyObject { }

Object Header {
  timestamp: int
  id: int
}

Object KitchenRelay{
  state: int '0'
}

PubSubMessage TemperatureMsg{
  temperature: float '0.0'
}

PubSubMessage HumidityMsg{
  humidity: float '0.0'
}

PubSubMessage IntruderMsg{
  positionX: int
  positionY: int
}

PubSubMessage RobotMsg{
  translationX: int '0'
  translationY: int '0'
  translationZ: int '0'
  orientationX: int '0'
  orientationY: int '0'
  orientationZ: int '0'
}

PubSubMessage UnusedMsg{
  rotationX: float
  rotationY: float
  is_rotated: int
}

RPCMessage KitchenMsgR {
  data: KitchenRelay
  header: Header
  ---
  data: EmptyObject
  header: Header
}